### ISSUE TITLE
Doesn't seem to support `using` and `import` 

### ISSUE THREAD

**Issue by ImVexed** [norgor/vscode-capnp#3]
Using https://github.com/capnproto/go-capnp with a .capnp header of:
```
using Go = import "/go.capnp";
$Go.package("rpc");
$Go.import("rpc");
```
shows
![image](https://github.com/norgor/vscode-capnp/assets/10090878/a5d45b34-0f68-438f-b67e-8820e59eba85)

**Comment by ngorke** [comment]
I presume you use the -I option when compiling the file?

Support for that would have to be added in the extension, as it does not know where to look for the files.

**Comment by ngorke** [comment]
Support for this has now been added as of 0.2.0 with commit d7e33b5. You can now configue import paths by using the `capnp.importPath` configuration.

Hope this helps!
