### ISSUE TITLE
Improper syntax highlighting for nested interfaces

### ISSUE THREAD

**Issue by bogdan-deac** [norgor/vscode-capnp#4]
Hi, cool project, really came in handy!

I noticed a small issue while playing around with some nested interfaces. While not anywhere near breaking, it's kind of annoying.

<img width="766" alt="Screenshot 2024-04-27 at 20 31 20" src="https://github.com/norgor/vscode-capnp/assets/108991148/63ed66d6-3ef2-44f9-ae06-589ba766ab57">

In this block of code, RaftTransport is a top level interface with two nested interfaces (was trying our some stuf based on the [docs](https://capnproto.org/news/2020-04-23-capnproto-0.8.html#:~:text=tweaks%20and%20fixes.-,Multi%2Dstream%20Flow%20Control,-It%20is%20commonly)). 

The first inner interface is not highlighted (only the "interface RecCallback" part, the rest works fine). The second one is highlighted.

**Comment by ngorke** [comment]
Hey!

Glad you like the project!

Thanks for reporting the issue. I am quite busy at the moment, but I will look into the bug when I have the time. You are also free to make a pull request if you would like.

**Comment by ngorke** [comment]
Hi again! 

This should now have been fixed in version 0.2.0 by commit b9176a0.

Thanks for reporting the bug.
